steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'git clone'
  script: |
    git clone https://github.com/yaoxiaoqi/tf-test.git

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get binary'
  script: |
    mkdir bin
    gsutil cp gs://seven-tf-provider-bin/bin/terraform-provider-google bin/terraform-provider-google
    cd bin
    chmod +x terraform-provider-google

- name: 'hashicorp/terraform:latest'
  id: 'Terraform Init'
  script: |
    pwd
    touch tf-dev-override.tfrc
    cat << EOF > tf-dev-override.tfrc
    provider_installation {

      # Developer overrides will stop Terraform from downloading the listed
      # providers their origin provider registries.
      dev_overrides {
          "hashicorp/google" = "/workspace/bin"
      }

      # For all other providers, install them directly from their origin provider
      # registries as normal. If you omit this, Terraform will _only_ use
      # the dev_overrides block, and so no other providers will be available.
      direct {}
    }
    EOF
    # This command initializes Terraform and configures the GCS backend.
    # Because it's running in Cloud Build, it automatically uses the
    # build service account's credentials (which you set in Step 2).
    cd tf-test
    terraform init
    TF_CLI_CONFIG_FILE="/workspace/tf-dev-override.tfrc" terraform plan
    TF_CLI_CONFIG_FILE="/workspace/tf-dev-override.tfrc" terraform apply -auto-approve

# - name: 'hashicorp/terraform:1.0.0'
#   id: 'Terraform Plan'
#   args: ['plan', '-out=tf.plan']

# # This specifies that artifacts from the build (the plan file)
# # should be available to subsequent steps.
# artifacts:
#   objects:
#     location: 'gs://$PROJECT_ID-cloudbuild/artifacts'
#     paths: ['tf.plan']
